binop_separator = "Back"
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
