name: CI

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update toolchains
      run: |
        rustup update stable
        rustup update nightly
        rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
        rustup default stable
    - name: Check formatting
      run: cargo +nightly fmt --all --check
    - name: Run unit tests
      run: cargo test
